name = "Whisper 2"
license = "MIT"
licenselink = "https://github.com/NickolasHKraus/whisper-2/blob/master/LICENSE"
description = "A minimalist documentation theme for Hugo. Whisper 2 is hyper-performant and fully open-source.",
homepage = "https://github.com/NickolasHKraus/whisper-2"
tags = []
features = []
min_version = 0.55.4

[author]
  name = "Nickolas Kraus"
  homepage = "https://github.com/NickolasHKraus"
  repo = "https://github.com/NickolasHKraus/whisper-2"

[original]
  name = "Robert Austin"
  homepage = "https://github.com/JugglerX"
  repo = "https://github.com/JugglerX/hugo-whisper-theme"
